"""Convert a PNG to an LVGL 9 RGB565 C array.

Usage: python png2lvgl.py input.png output_basename var_name
Writes <output_basename>.c / .h next to the output path.

For RGBA sources, composite over the splash background first, e.g.:
    im = im.resize((320, 320), Image.LANCZOS)
    out = Image.alpha_composite(Image.new('RGBA', im.size, (15, 17, 21, 255)), im)
"""
import sys
from PIL import Image

def main():
    src, out_base, var = sys.argv[1], sys.argv[2], sys.argv[3]
    img = Image.open(src).convert("RGB")
    w, h = img.size
    px = img.load()

    data = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            data += bytes((v & 0xFF, v >> 8))  # little-endian RGB565

    lines = []
    for i in range(0, len(data), 24):
        lines.append(", ".join(f"0x{b:02X}" for b in data[i:i+24]))
    body = ",\n    ".join(lines)

    with open(out_base + ".c", "w") as f:
        f.write(f"""// Auto-generated by tools/png2lvgl.py from {src.split(chr(92))[-1]} — do not edit.
#include "lvgl.h"

static const uint8_t {var}_map[] = {{
    {body}
}};

const lv_image_dsc_t {var} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = {w},
        .h = {h},
        .stride = {w * 2},
    }},
    .data_size = sizeof({var}_map),
    .data = {var}_map,
}};
""")
    with open(out_base + ".h", "w") as f:
        guard = var.upper() + "_H"
        f.write(f"""#pragma once
#include "lvgl.h"

extern const lv_image_dsc_t {var};
""")
    print(f"wrote {out_base}.c ({len(data)} bytes, {w}x{h})")

if __name__ == "__main__":
    main()
